### ISSUE TITLE
EntityUtils.getMappedEntities not compatible with hibernate 5

### ISSUE THREAD

**Issue by ayslanms** [xpert-framework/xpert-framework#15]
The following error occurs:

```java
java.lang.UnsupportedOperationException: org.hibernate.SessionFactory.getAllClassMetadata is no longer supported
	at org.hibernate.internal.SessionFactoryImpl.getAllClassMetadata(SessionFactoryImpl.java:700)
	at com.xpert.persistence.utils.EntityUtils.getMappedEntities(EntityUtils.java:128)
```

**Comment by ayslanms** [comment]
Solution: Remove hiberate classes and use  entityManagerFactory.getMetamodel()
